#!/usr/bin/python3
from time import sleep
def out_come():
    print(" Welcome to the world of searching knowledge and skills : ")
    print("At the end of the program you should be able to :")
    print("")
    sleep(2)
    print("1. Write and spell the alphabets")
    sleep(2)
    print("2. Connect multiple alphabets to make a spelled word")
    sleep(2)
    print("3. write the names of things that surround you")
    sleep(2)
    print("4. Communicate through writting")
    sleep(2)
    print("5. You should have the basic skills to perform well the rest of your education journey")
    sleep(2)
    print("6. Listen some words from Radios and television")
    sleep(2)
    print("Now, it is time to starts the program, welcome!")
    print("")
    sleep(1)

